name: RunicOverlord
version: '1.0-SNAPSHOT'
main: com.trevorfarias.runic_overlord.RunicOverlord
api-version: '1.21'

commands:
  givecustom:
    description: Gives custom items (vouchers, runes, gear, identifiers, wands)
    usage: /<command> <voucher|rune|gear|identifier|wand> <id?> [unidentified]
    permission: runicoverlord.admin
    permission-message: §cYou must be an admin to use this command.
  sellfish:
    description: Sells every fish in your inventory for Vault currency
    aliases: [sfish]
    usage: /<command>
    permission: runicoverlord.default
  fishlevel:
    description: Check current fishing level
    usage: /fl
    permission: runicoverlord.default
  rofishing:
    description: Admin-only subcommand set (currently just “reload”)
    usage: /rofishing reload
    permission: runicoverlord.admin
  rofsetlevel:
    description: Set a player’s fishing level
    usage: /rofsetlevel <player> <level>
    permission: runicoverlord.admin
  fish:
    description: Instantly hook & reel one fish (internal helper for Willow’s Rod)
    usage: /fish
    permission: runicoverlord.admin
  rofgear:
    description: Reloads gear config from gear.yml
    usage: /rofgear reload
    permission: runicoverlord.reloadgear
  li:
    description: Lists available custom gear
    usage: /li
    permission: runicoverlord.default